[package]
name = "rust-passport-azure-ad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
poem = "1.3.55"
jws = "0.2.7"
hex = "0.4.3"
base64 = "0.21.2"
xmltree = "0.10.3"
regex = "1.8.3"
base64-url = "2.0.0"
rand = "0.8.5"
sha256 = "1.1.3"
chrono = "0.4.26"
url = "2.3.1"
reqwest = { version = "0.11.18", features = ["json"] }
alcoholic_jwt = "4091.0.0"
